name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: KRdahee
          outputs: |
            dist/github-snake.gif?color_snake=#ff6a00&color_dots=#2A2422,#331a00,#803300,#cc5200,#ff6a00&color_background=#00ff00

      - name: Remove GIF Background
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

          magick dist/github-snake.gif \
            -coalesce \
            -alpha on \
            -fuzz 1% \
            -transparent "#00ff00" \
            -layers Optimize \
            dist/github-snake-transparent.gif

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
